version: "3.2"
services:
##################################
# MySQL Server
##################################
  mysql-db:
    image: mysql:8.0.1
    # container_name: "default-mysql"
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3306:3306
    environment:
      # MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: varys
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    volumes:
        - "mysql-data:/var/lib/mysql"
        - "mysql-outfiles:/home/outfiles"
        - "./my.cnf:/etc/mysql/my.cnf"
##################################
# PHP MySQL Admin
##################################
  mysql-admin-console:
    image: phpmyadmin/phpmyadmin
    # container_name: "default-mysql-admin-console"
    restart: always
    ports:
      - 8080:80
    environment:
      # MYSQL_ROOT_PASSWORD: root
      PMA_HOST: mysql-db
volumes:
  mysql-data:
  mysql-outfiles:
################################################################################
##
##
# this compose file is created with the help of the mysql docker hub page
# for more help, refer https://hub.docker.com/_/mysql
##
##
################################################################################
